### ISSUE TITLE
how to train with 100% label?

### ISSUE THREAD

**Issue by gehaoran-dev** [Na-Z/sess#15]
Hi @Na-Z，thanks for sharing this great work.
how to train with 100% label?
When I set labeled_ratio_list to [1. 0] for training，valueerror: num samples should be a positive integer value, but got num sample = 0.Then I set “shuffle” in dateloader to false, an error is still reported. I hope to get your suggestions

**Comment by Na-Z** [comment]
Hi @gehaoran-dev,

If you would like to train with 100% labels, you just need to remove those parts related to `UNLABELED_DATASET` in `train_sess.py `.

For example: 
1. Do not create `UNLABELED_DATASET` in `train_sess.py `.
2. Modify https://github.com/Na-Z/sess/blob/f1bbb44ea6ed73bb71bce12f54ca9bc33746dce8/train_sess.py#L241-L251 as ```for batch_idx, batch_data_label in enumerate(LABELED_DATALOADER):```, since we only iterate over labeled dataset.

Hope this solves your problem.

**Comment by gehaoran-dev** [comment]
Thank you for the quick reply~
